package org.taktik.icure.fhir.deserializer

import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.ObjectCodec
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonNode
import org.springframework.boot.jackson.JsonObjectDeserializer
import org.taktik.icure.fhir.entities.r4.Resource

class FhirResourceDeserializer : JsonObjectDeserializer<Resource>() {
    override fun deserializeObject(jsonParser: JsonParser,
        context: DeserializationContext,
        codec: ObjectCodec,
        tree: JsonNode): Resource {
        return when(tree["resourceType"]?.asText()) {
            "Account" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.account.Account::class.java)
            "ActivityDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.activitydefinition.ActivityDefinition::class.java)
            "AdverseEvent" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.adverseevent.AdverseEvent::class.java)
            "AllergyIntolerance" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.allergyintolerance.AllergyIntolerance::class.java)
            "Appointment" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.appointment.Appointment::class.java)
            "AppointmentResponse" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.appointmentresponse.AppointmentResponse::class.java)
            "AuditEvent" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.auditevent.AuditEvent::class.java)
            "Basic" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.basic.Basic::class.java)
            "Binary" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.binary.Binary::class.java)
            "BiologicallyDerivedProduct" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.biologicallyderivedproduct.BiologicallyDerivedProduct::class.java)
            "BodyStructure" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.bodystructure.BodyStructure::class.java)
            "Bundle" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.bundle.Bundle::class.java)
            "CapabilityStatement" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.capabilitystatement.CapabilityStatement::class.java)
            "CarePlan" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.careplan.CarePlan::class.java)
            "CareTeam" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.careteam.CareTeam::class.java)
            "CatalogEntry" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.catalogentry.CatalogEntry::class.java)
            "ChargeItem" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.chargeitem.ChargeItem::class.java)
            "ChargeItemDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.chargeitemdefinition.ChargeItemDefinition::class.java)
            "Claim" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.claim.Claim::class.java)
            "ClaimResponse" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.claimresponse.ClaimResponse::class.java)
            "ClinicalImpression" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.clinicalimpression.ClinicalImpression::class.java)
            "CodeSystem" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.codesystem.CodeSystem::class.java)
            "Communication" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.communication.Communication::class.java)
            "CommunicationRequest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.communicationrequest.CommunicationRequest::class.java)
            "CompartmentDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.compartmentdefinition.CompartmentDefinition::class.java)
            "Composition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.composition.Composition::class.java)
            "ConceptMap" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.conceptmap.ConceptMap::class.java)
            "Condition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.condition.Condition::class.java)
            "Consent" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.consent.Consent::class.java)
            "Contract" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.contract.Contract::class.java)
            "Coverage" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.coverage.Coverage::class.java)
            "CoverageEligibilityRequest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.coverageeligibilityrequest.CoverageEligibilityRequest::class.java)
            "CoverageEligibilityResponse" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.coverageeligibilityresponse.CoverageEligibilityResponse::class.java)
            "DetectedIssue" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.detectedissue.DetectedIssue::class.java)
            "Device" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.device.Device::class.java)
            "DeviceDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.devicedefinition.DeviceDefinition::class.java)
            "DeviceMetric" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.devicemetric.DeviceMetric::class.java)
            "DeviceRequest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.devicerequest.DeviceRequest::class.java)
            "DeviceUseStatement" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.deviceusestatement.DeviceUseStatement::class.java)
            "DiagnosticReport" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.diagnosticreport.DiagnosticReport::class.java)
            "DocumentManifest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.documentmanifest.DocumentManifest::class.java)
            "DocumentReference" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.documentreference.DocumentReference::class.java)
            "EffectEvidenceSynthesis" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.effectevidencesynthesis.EffectEvidenceSynthesis::class.java)
            "Encounter" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.encounter.Encounter::class.java)
            "Endpoint" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.endpoint.Endpoint::class.java)
            "EnrollmentRequest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.enrollmentrequest.EnrollmentRequest::class.java)
            "EnrollmentResponse" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.enrollmentresponse.EnrollmentResponse::class.java)
            "EpisodeOfCare" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.episodeofcare.EpisodeOfCare::class.java)
            "EventDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.eventdefinition.EventDefinition::class.java)
            "Evidence" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.evidence.Evidence::class.java)
            "EvidenceVariable" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.evidencevariable.EvidenceVariable::class.java)
            "ExampleScenario" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.examplescenario.ExampleScenario::class.java)
            "ExplanationOfBenefit" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.explanationofbenefit.ExplanationOfBenefit::class.java)
            "FamilyMemberHistory" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.familymemberhistory.FamilyMemberHistory::class.java)
            "Flag" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.flag.Flag::class.java)
            "Goal" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.goal.Goal::class.java)
            "GraphDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.graphdefinition.GraphDefinition::class.java)
            "Group" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.group.Group::class.java)
            "GuidanceResponse" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.guidanceresponse.GuidanceResponse::class.java)
            "HealthcareService" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.healthcareservice.HealthcareService::class.java)
            "ImagingStudy" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.imagingstudy.ImagingStudy::class.java)
            "Immunization" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.immunization.Immunization::class.java)
            "ImmunizationEvaluation" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.immunizationevaluation.ImmunizationEvaluation::class.java)
            "ImmunizationRecommendation" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.immunizationrecommendation.ImmunizationRecommendation::class.java)
            "ImplementationGuide" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.implementationguide.ImplementationGuide::class.java)
            "InsurancePlan" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.insuranceplan.InsurancePlan::class.java)
            "Invoice" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.invoice.Invoice::class.java)
            "Library" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.library.Library::class.java)
            "Linkage" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.linkage.Linkage::class.java)
            "Location" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.location.Location::class.java)
            "Measure" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.measure.Measure::class.java)
            "MeasureReport" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.measurereport.MeasureReport::class.java)
            "Media" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.media.Media::class.java)
            "Medication" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medication.Medication::class.java)
            "MedicationAdministration" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicationadministration.MedicationAdministration::class.java)
            "MedicationDispense" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicationdispense.MedicationDispense::class.java)
            "MedicationKnowledge" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicationknowledge.MedicationKnowledge::class.java)
            "MedicationRequest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicationrequest.MedicationRequest::class.java)
            "MedicationStatement" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicationstatement.MedicationStatement::class.java)
            "MedicinalProduct" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproduct.MedicinalProduct::class.java)
            "MedicinalProductAuthorization" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductauthorization.MedicinalProductAuthorization::class.java)
            "MedicinalProductContraindication" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductcontraindication.MedicinalProductContraindication::class.java)
            "MedicinalProductIndication" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductindication.MedicinalProductIndication::class.java)
            "MedicinalProductIngredient" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductingredient.MedicinalProductIngredient::class.java)
            "MedicinalProductInteraction" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductinteraction.MedicinalProductInteraction::class.java)
            "MedicinalProductManufactured" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductmanufactured.MedicinalProductManufactured::class.java)
            "MedicinalProductPackaged" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductpackaged.MedicinalProductPackaged::class.java)
            "MedicinalProductPharmaceutical" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductpharmaceutical.MedicinalProductPharmaceutical::class.java)
            "MedicinalProductUndesirableEffect" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.medicinalproductundesirableeffect.MedicinalProductUndesirableEffect::class.java)
            "MessageDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.messagedefinition.MessageDefinition::class.java)
            "MessageHeader" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.messageheader.MessageHeader::class.java)
            "MetadataResource" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.metadataresource.MetadataResource::class.java)
            "MolecularSequence" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.molecularsequence.MolecularSequence::class.java)
            "NamingSystem" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.namingsystem.NamingSystem::class.java)
            "NutritionOrder" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.nutritionorder.NutritionOrder::class.java)
            "Observation" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.observation.Observation::class.java)
            "ObservationDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.observationdefinition.ObservationDefinition::class.java)
            "OperationDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.operationdefinition.OperationDefinition::class.java)
            "OperationOutcome" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.operationoutcome.OperationOutcome::class.java)
            "Organization" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.organization.Organization::class.java)
            "OrganizationAffiliation" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.organizationaffiliation.OrganizationAffiliation::class.java)
            "Parameters" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.parameters.Parameters::class.java)
            "Patient" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.patient.Patient::class.java)
            "PaymentNotice" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.paymentnotice.PaymentNotice::class.java)
            "PaymentReconciliation" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.paymentreconciliation.PaymentReconciliation::class.java)
            "Person" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.person.Person::class.java)
            "PlanDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.plandefinition.PlanDefinition::class.java)
            "Practitioner" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.practitioner.Practitioner::class.java)
            "PractitionerRole" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.practitionerrole.PractitionerRole::class.java)
            "Procedure" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.procedure.Procedure::class.java)
            "Provenance" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.provenance.Provenance::class.java)
            "Questionnaire" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.questionnaire.Questionnaire::class.java)
            "QuestionnaireResponse" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.questionnaireresponse.QuestionnaireResponse::class.java)
            "RelatedPerson" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.relatedperson.RelatedPerson::class.java)
            "RequestGroup" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.requestgroup.RequestGroup::class.java)
            "ResearchDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.researchdefinition.ResearchDefinition::class.java)
            "ResearchElementDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.researchelementdefinition.ResearchElementDefinition::class.java)
            "ResearchStudy" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.researchstudy.ResearchStudy::class.java)
            "ResearchSubject" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.researchsubject.ResearchSubject::class.java)
            "RiskAssessment" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.riskassessment.RiskAssessment::class.java)
            "RiskEvidenceSynthesis" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.riskevidencesynthesis.RiskEvidenceSynthesis::class.java)
            "Schedule" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.schedule.Schedule::class.java)
            "SearchParameter" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.searchparameter.SearchParameter::class.java)
            "ServiceRequest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.servicerequest.ServiceRequest::class.java)
            "Slot" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.slot.Slot::class.java)
            "Specimen" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.specimen.Specimen::class.java)
            "SpecimenDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.specimendefinition.SpecimenDefinition::class.java)
            "StructureDefinition" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.structuredefinition.StructureDefinition::class.java)
            "StructureMap" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.structuremap.StructureMap::class.java)
            "Subscription" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.subscription.Subscription::class.java)
            "Substance" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.substance.Substance::class.java)
            "SubstanceNucleicAcid" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.substancenucleicacid.SubstanceNucleicAcid::class.java)
            "SubstancePolymer" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.substancepolymer.SubstancePolymer::class.java)
            "SubstanceProtein" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.substanceprotein.SubstanceProtein::class.java)
            "SubstanceReferenceInformation" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.substancereferenceinformation.SubstanceReferenceInformation::class.java)
            "SubstanceSourceMaterial" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.substancesourcematerial.SubstanceSourceMaterial::class.java)
            "SubstanceSpecification" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.substancespecification.SubstanceSpecification::class.java)
            "SupplyDelivery" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.supplydelivery.SupplyDelivery::class.java)
            "SupplyRequest" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.supplyrequest.SupplyRequest::class.java)
            "Task" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.task.Task::class.java)
            "TerminologyCapabilities" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.terminologycapabilities.TerminologyCapabilities::class.java)
            "TestReport" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.testreport.TestReport::class.java)
            "TestScript" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.testscript.TestScript::class.java)
            "ValueSet" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.valueset.ValueSet::class.java)
            "VerificationResult" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.verificationresult.VerificationResult::class.java)
            "VisionPrescription" -> codec.treeToValue(tree, org.taktik.icure.fhir.entities.r4.visionprescription.VisionPrescription::class.java)
           else -> throw IllegalArgumentException("Unknown resource")
        }
    }
}
