//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.29 at 05:57:25 PM CEST
//


package org.taktik.freehealth.middleware.dto.memberdata

import org.taktik.icure.cin.saml.oasis.names.tc.saml._2_0.assertion.AdviceType
import org.taktik.icure.cin.saml.oasis.names.tc.saml._2_0.assertion.Conditions
import org.taktik.icure.cin.saml.oasis.names.tc.saml._2_0.assertion.NameIDType
import org.taktik.icure.cin.saml.oasis.names.tc.saml._2_0.assertion.StatementAbstractType
import org.taktik.icure.cin.saml.oasis.names.tc.saml._2_0.assertion.Subject
import org.taktik.icure.cin.saml.org.w3._2000._09.xmldsig_.Signature
import java.io.Serializable
import java.util.ArrayList

class AssertionDto(var issuer: NameIDType? = null, var signature: Signature? = null, var subject: Subject? = null,
    var conditions: Conditions? = null, var advice: AdviceType? = null,
    var statementsAndAuthnStatementsAndAuthzDecisionStatements: List<StatementAbstractType> = ArrayList(),
    var version: String? = null, var id: String? = null, var issueInstant: Long? = null) : Serializable
