package org.taktik.freehealth.middleware.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1


import org.taktik.freehealth.middleware.drugs.dto.DocId;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

/**
 * Doc generated by hbm2java
 */
public class Doc  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private DocId id;
     private Doc parent;
     private String hierarchy;
     private Integer docindex;
     private Boolean mpgrp;
     private String title;
     private String content;
     private String pos;
     private String type;
     //private Set<Mpp> mpps = new HashSet<Mpp>(0);
     private List<Doc> children = new ArrayList<Doc>(0);
     private Set<Composition> compositions = new HashSet<Composition>(0);
     private SortedSet<Mp> mps = new TreeSet<Mp>();

    public Doc() {
    }

    public DocId getId() {
        return this.id;
    }
    
    public void setId(DocId id) {
        this.id = id;
    }
    public String getHierarchy() {
        return this.hierarchy;
    }
    
    public void setHierarchy(String hierarchy) {
        this.hierarchy = hierarchy;
    }
    public Integer getDocindex() {
        return this.docindex;
    }
    
    public void setDocindex(Integer docindex) {
        this.docindex = docindex;
    }
    public Boolean getMpgrp() {
        return this.mpgrp;
    }
    
    public void setMpgrp(Boolean mpgrp) {
        this.mpgrp = mpgrp;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getPos() {
        return this.pos;
    }
    
    public void setPos(String pos) {
        this.pos = pos;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
//    public Set<Mpp> getMpps() {
//        return this.mpps;
//    }
//    
//    public void setMpps(Set<Mpp> mpps) {
//        this.mpps = mpps;
//    }

    public Set<Composition> getCompositions() {
        return this.compositions;
    }
    
    public void setCompositions(Set<Composition> compositions) {
        this.compositions = compositions;
    }
    public SortedSet<Mp> getMps() {
        return this.mps;
    }
    
    public void setMps(SortedSet<Mp> mps) {
        this.mps = mps;
    }

	public List<Doc> getChildren() {
		return children;
	}

	public void setChildren(List<Doc> children) {
		this.children = children;
	}

	public Doc getParent() {
		return parent;
	}

	public void setParent(Doc parent) {
		this.parent = parent;
	}

}


