package org.taktik.freehealth.middleware.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1


import org.taktik.freehealth.middleware.drugs.dto.EquivalenceId;

/**
 * Equivalence generated by hbm2java
 */
public class Equivalence  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private EquivalenceId id;
     private Mp mpBySourceequivalence;
     private Mp mpByTargetequivalence;
     private String type;

    public Equivalence() {
    }

	
    public Equivalence(EquivalenceId id, Mp mpBySourceequivalence, Mp mpByTargetequivalence) {
        this.id = id;
        this.mpBySourceequivalence = mpBySourceequivalence;
        this.mpByTargetequivalence = mpByTargetequivalence;
    }
    public Equivalence(EquivalenceId id, Mp mpBySourceequivalence, Mp mpByTargetequivalence, String type) {
       this.id = id;
       this.mpBySourceequivalence = mpBySourceequivalence;
       this.mpByTargetequivalence = mpByTargetequivalence;
       this.type = type;
    }
   
    public EquivalenceId getId() {
        return this.id;
    }
    
    public void setId(EquivalenceId id) {
        this.id = id;
    }
    public Mp getMpBySourceequivalence() {
        return this.mpBySourceequivalence;
    }
    
    public void setMpBySourceequivalence(Mp mpBySourceequivalence) {
        this.mpBySourceequivalence = mpBySourceequivalence;
    }
    public Mp getMpByTargetequivalence() {
        return this.mpByTargetequivalence;
    }
    
    public void setMpByTargetequivalence(Mp mpByTargetequivalence) {
        this.mpByTargetequivalence = mpByTargetequivalence;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


