package org.taktik.freehealth.middleware.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1


import org.taktik.freehealth.middleware.drugs.dto.GalId;

/**
 * Gal generated by hbm2java
 */
public class Gal  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private GalId id;
     private String name;
     private Boolean deleted;
     private String type;

    public Gal() {
    }

	
    public Gal(GalId id) {
        this.id = id;
    }

   
    public GalId getId() {
        return this.id;
    }
    
    public void setId(GalId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }


}


