package org.taktik.freehealth.middleware.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1


import org.taktik.freehealth.middleware.drugs.dto.IngredientId;

import java.util.HashSet;
import java.util.Set;

/**
 * Ingredient generated by hbm2java
 */
public class Ingredient  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private IngredientId id;
     private String name;
     private String note;
     private Boolean deleted;
     private String type;
     private Set<Composition> compositions = new HashSet<Composition>(0);

    public Ingredient() {
    }

   
    public IngredientId getId() {
        return this.id;
    }
    
    public void setId(IngredientId id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Boolean getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<Composition> getCompositions() {
        return this.compositions;
    }
    
    public void setCompositions(Set<Composition> compositions) {
        this.compositions = compositions;
    }




}


