package org.taktik.freehealth.middleware.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1


import org.taktik.freehealth.middleware.drugs.dto.MpppropId;

/**
 * Mppprop generated by hbm2java
 */
public class Mppprop  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private MpppropId id;
     private Mpp mpp;
     private String strprop;
     private Double nbprop;
     private String type;

    public Mppprop() {
    }

	
    public Mppprop(MpppropId id, Mpp mpp) {
        this.id = id;
        this.mpp = mpp;
    }
    public Mppprop(MpppropId id, Mpp mpp, String strprop, Double nbprop, String type) {
       this.id = id;
       this.mpp = mpp;
       this.strprop = strprop;
       this.nbprop = nbprop;
       this.type = type;
    }
   
    public MpppropId getId() {
        return this.id;
    }
    
    public void setId(MpppropId id) {
        this.id = id;
    }
    public Mpp getMpp() {
        return this.mpp;
    }
    
    public void setMpp(Mpp mpp) {
        this.mpp = mpp;
    }
    public String getStrprop() {
        return this.strprop;
    }
    
    public void setStrprop(String strprop) {
        this.strprop = strprop;
    }
    public Double getNbprop() {
        return this.nbprop;
    }
    
    public void setNbprop(Double nbprop) {
        this.nbprop = nbprop;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


