package org.taktik.freehealth.middleware.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1



/**
 * Prop generated by hbm2java
 */
public class Prop  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private String key;
     private String value;

    public Prop() {
    }

	
    public Prop(String key) {
        this.key = key;
    }
    public Prop(String key, String value) {
       this.key = key;
       this.value = value;
    }
   
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


