package be.ehealth.businessconnector.mediprimauma.service;

import be.ehealth.businessconnector.mediprimauma.exception.MediprimaUmaDeleteException;
import be.ehealth.businessconnector.mediprimauma.exception.MediprimaUmaSearchException;
import be.ehealth.businessconnector.mediprimauma.exception.MediprimaUmaSendException;
import be.ehealth.technicalconnector.exception.TechnicalConnectorException;
import be.ehealth.technicalconnector.service.sts.security.SAMLToken;
import be.fgov.ehealth.mediprima.uma.protocol.v1.DeleteUrgentMedicalAidAttestationRequest;
import be.fgov.ehealth.mediprima.uma.protocol.v1.DeleteUrgentMedicalAidAttestationResponse;
import be.fgov.ehealth.mediprima.uma.protocol.v1.SearchUrgentMedicalAidAttestationRequest;
import be.fgov.ehealth.mediprima.uma.protocol.v1.SearchUrgentMedicalAidAttestationResponse;
import be.fgov.ehealth.mediprima.uma.protocol.v1.SendUrgentMedicalAidAttestationRequest;
import be.fgov.ehealth.mediprima.uma.protocol.v1.SendUrgentMedicalAidAttestationResponse;

public interface MediprimaUmaService {
   DeleteUrgentMedicalAidAttestationResponse deleteUrgentMedicalAidAttestation(SAMLToken var1, DeleteUrgentMedicalAidAttestationRequest var2) throws MediprimaUmaDeleteException, TechnicalConnectorException;

   SearchUrgentMedicalAidAttestationResponse searchUrgentMedicalAidAttestation(SAMLToken var1, SearchUrgentMedicalAidAttestationRequest var2) throws MediprimaUmaSearchException, TechnicalConnectorException;

   SendUrgentMedicalAidAttestationResponse sendUrgentMedicalAidAttestation(SAMLToken var1, SendUrgentMedicalAidAttestationRequest var2) throws MediprimaUmaSendException, TechnicalConnectorException;
}
