
package be.fgov.ehealth.daas.saml.protocol.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import oasis.names.tc.saml._2_0.protocol.AttributeQueryType;
import oasis.names.tc.saml._2_0.protocol.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataAttributeServicePortType", targetNamespace = "urn:be:fgov:ehealth:daas:saml:protocol:v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    oasis.names.tc.saml._2_0.assertion.ObjectFactory.class,
    oasis.names.tc.saml._2_0.protocol.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    org.w3._2001._04.xmlenc_.ObjectFactory.class
})
public interface DataAttributeServicePortType {


    /**
     * 
     * @param body
     * @return
     *     returns oasis.names.tc.saml._2_0.protocol.ResponseType
     */
    @WebMethod(operationName = "AttributeQuery", action = "urn:be:fgov:ehealth:daas:saml:protocol:v1:AttributeQuery")
    @WebResult(name = "Response", targetNamespace = "urn:oasis:names:tc:SAML:2.0:protocol", partName = "body")
    public ResponseType attributeQuery(
        @WebParam(name = "AttributeQuery", targetNamespace = "urn:oasis:names:tc:SAML:2.0:protocol", partName = "body")
        AttributeQueryType body);

}
