
package be.fgov.ehealth.daas.saml.protocol.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataAttributeService", targetNamespace = "urn:be:fgov:ehealth:daas:saml:protocol:v1", wsdlLocation = "file:/Users/aduchate/Sources/icure/freehealth-connector/src/main/resources/ehealth-daas/WSDL/ehealth-daas-saml2-DataAttributeService-proxy-v1.wsdl")
public class DataAttributeService
    extends Service
{

    private final static URL DATAATTRIBUTESERVICE_WSDL_LOCATION;
    private final static WebServiceException DATAATTRIBUTESERVICE_EXCEPTION;
    private final static QName DATAATTRIBUTESERVICE_QNAME = new QName("urn:be:fgov:ehealth:daas:saml:protocol:v1", "DataAttributeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/aduchate/Sources/icure/freehealth-connector/src/main/resources/ehealth-daas/WSDL/ehealth-daas-saml2-DataAttributeService-proxy-v1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATAATTRIBUTESERVICE_WSDL_LOCATION = url;
        DATAATTRIBUTESERVICE_EXCEPTION = e;
    }

    public DataAttributeService() {
        super(__getWsdlLocation(), DATAATTRIBUTESERVICE_QNAME);
    }

    public DataAttributeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATAATTRIBUTESERVICE_QNAME, features);
    }

    public DataAttributeService(URL wsdlLocation) {
        super(wsdlLocation, DATAATTRIBUTESERVICE_QNAME);
    }

    public DataAttributeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATAATTRIBUTESERVICE_QNAME, features);
    }

    public DataAttributeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataAttributeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataAttributeServicePortType
     */
    @WebEndpoint(name = "DataAttributeServicePort")
    public DataAttributeServicePortType getDataAttributeServicePort() {
        return super.getPort(new QName("urn:be:fgov:ehealth:daas:saml:protocol:v1", "DataAttributeServicePort"), DataAttributeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataAttributeServicePortType
     */
    @WebEndpoint(name = "DataAttributeServicePort")
    public DataAttributeServicePortType getDataAttributeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:be:fgov:ehealth:daas:saml:protocol:v1", "DataAttributeServicePort"), DataAttributeServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATAATTRIBUTESERVICE_EXCEPTION!= null) {
            throw DATAATTRIBUTESERVICE_EXCEPTION;
        }
        return DATAATTRIBUTESERVICE_WSDL_LOCATION;
    }

}
