//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 09:24:52 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.recipe.be", elementFormDefault = XmlNsForm.UNQUALIFIED)
package org.taktik.connector.business.domain.kmehr.v20161201.be.ehealth.logic.recipe.xsd.v20160906;

import javax.xml.bind.annotation.XmlNsForm;