package org.taktik.freehealth.middleware.drugs.dto;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1



/**
 * EquivalenceId generated by hbm2java
 */
public class EquivalenceId  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private String mpId;
     private String eqmpId;
     private String lang;

    public EquivalenceId() {
    }

    public EquivalenceId(String mpId, String eqmpId, String lang) {
       this.mpId = mpId;
       this.eqmpId = eqmpId;
       this.lang = lang;
    }
   
    public String getMpId() {
        return this.mpId;
    }
    
    public void setMpId(String mpId) {
        this.mpId = mpId;
    }
    public String getEqmpId() {
        return this.eqmpId;
    }
    
    public void setEqmpId(String eqmpId) {
        this.eqmpId = eqmpId;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String lang) {
        this.lang = lang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EquivalenceId) ) return false;
		 EquivalenceId castOther = ( EquivalenceId ) other; 
         
		 return ( (this.getMpId()==castOther.getMpId()) || ( this.getMpId()!=null && castOther.getMpId()!=null && this.getMpId().equals(castOther.getMpId()) ) )
 && ( (this.getEqmpId()==castOther.getEqmpId()) || ( this.getEqmpId()!=null && castOther.getEqmpId()!=null && this.getEqmpId().equals(castOther.getEqmpId()) ) )
 && ( (this.getLang()==castOther.getLang()) || ( this.getLang()!=null && castOther.getLang()!=null && this.getLang().equals(castOther.getLang()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMpId() == null ? 0 : this.getMpId().hashCode() );
         result = 37 * result + ( getEqmpId() == null ? 0 : this.getEqmpId().hashCode() );
         result = 37 * result + ( getLang() == null ? 0 : this.getLang().hashCode() );
         return result;
   }   


}


