<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:be:fgov:ehealth:daas:saml:protocol:v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:be:fgov:ehealth:daas:saml:protocol:v1">
  
  <documentation>Version v1</documentation>
  
  <wsp:Policy xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="SamlHok">
    <sp:AsymmetricBinding>
        <wsp:Policy>
            <sp:InitiatorToken>
                <wsp:Policy>
                    <!-- If the client framework supports sp:IssuedToken policy assertions, uncomment this block and comment the sp:SamlToken assertion -->
                    <!-- <sp:IssuedToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient"> -->
                    <!-- <sp:RequestSecurityTokenTemplate /> -->
                    <!-- <wsp:Policy /> -->
                    <!-- </sp:IssuedToken> -->
                    <sp:SamlToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                        <wsp:Policy>
                            <sp:WssSamlV11Token10/>
                        </wsp:Policy>
                    </sp:SamlToken>
                </wsp:Policy>
            </sp:InitiatorToken>
            <sp:RecipientToken>
                <wsp:Policy>
                    <sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                        <wsp:Policy>
                            <sp:WssX509V3Token10/>
                        </wsp:Policy>
                    </sp:X509Token>
                </wsp:Policy>
            </sp:RecipientToken>
            <sp:AlgorithmSuite>
                <wsp:Policy>
                    <sp:Basic256/>
                </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
                <wsp:Policy>
                    <sp:Lax/>
                </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp/>
            <sp:ProtectTokens/>
            <sp:OnlySignEntireHeadersAndBody/>
        </wsp:Policy>
    </sp:AsymmetricBinding>
    <sp:Wss10>
        <wsp:Policy>
            <sp:MustSupportRefKeyIdentifier/>
            <sp:MustSupportRefIssuerSerial/>
        </wsp:Policy>
    </sp:Wss10>
    <sp:SignedParts>
        <sp:Body/>
    </sp:SignedParts>
</wsp:Policy>
  <types>
    <xsd:schema>
      <xsd:import namespace="urn:oasis:names:tc:SAML:2.0:protocol" schemaLocation="../../external/XSD/saml-schema-protocol-2.0.xsd"/>
    </xsd:schema>
  </types>
  
  <message name="AttributeQueryMessage">
    <part element="samlp:AttributeQuery" name="body"/>
  </message>
  <message name="ResponseMessage">
    <part element="samlp:Response" name="body"/>
  </message>
  
  <portType name="DataAttributeServicePortType">
    <operation name="AttributeQuery">
      <input message="tns:AttributeQueryMessage"/>
      <output message="tns:ResponseMessage"/>
    </operation>
  </portType>
  
  <binding name="DataAttributeServiceSoapBinding" type="tns:DataAttributeServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="AttributeQuery">
      <soap:operation soapAction="urn:be:fgov:ehealth:daas:saml:protocol:v1:AttributeQuery"/>
      <input>
        <wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="#SamlHok"/>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  
  <service name="DataAttributeService">
    <port binding="tns:DataAttributeServiceSoapBinding" name="DataAttributeServicePort">
      <soap:address location="https://services.ehealth.fgov.be/DAtaAttributeService/v1"/>
    </port>
  </service>
  
</definitions>
