//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.02.03 at 10:56:17 AM CET
//


package be.vaccinnet.wupl.uplvaccinatiegegevens;

import be.fgov.ehealth.standards.kmehr.id.v1.IDKMEHR;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 *
 *                 FolderResultType bevat een id (een volgnummer), een code, een omschrijving en
 *                 een transaction element (bevat gegevens over de verwerking van de vaccinaties).
 *                 De code dient om aan te geven of de verwerking gelukt is, de omschrijving dient
 *                 om de code te verduidelijken.
 *
 *
 * <p>Java class for FolderResultType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FolderResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.ehealth.fgov.be/standards/kmehr/id/v1}ID-KMEHR" maxOccurs="unbounded"/&gt;
 *         &lt;element name="patient" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="patientTekst" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="transaction" type="{http://www.vaccinnet.be/wupl/UPLVaccinatieGegevens}TransactionResultType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FolderResultType", propOrder = {
    "id",
    "patient",
    "patientTekst",
    "transaction"
})
public class FolderResultType {

    @XmlElement(required = true)
    protected List<IDKMEHR> id;
    @XmlElement(required = true)
    protected String patient;
    protected String patientTekst;
    @XmlElement(required = true)
    protected List<TransactionResultType> transaction;

    /**
     * Gets the value of the id property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDKMEHR }
     *
     *
     */
    public List<IDKMEHR> getId() {
        if (id == null) {
            id = new ArrayList<IDKMEHR>();
        }
        return this.id;
    }

    /**
     * Gets the value of the patient property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPatient(String value) {
        this.patient = value;
    }

    /**
     * Gets the value of the patientTekst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPatientTekst() {
        return patientTekst;
    }

    /**
     * Sets the value of the patientTekst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPatientTekst(String value) {
        this.patientTekst = value;
    }

    /**
     * Gets the value of the transaction property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transaction property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransaction().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionResultType }
     *
     *
     */
    public List<TransactionResultType> getTransaction() {
        if (transaction == null) {
            transaction = new ArrayList<TransactionResultType>();
        }
        return this.transaction;
    }

}
