//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.02.03 at 10:56:17 AM CET
//


package be.vaccinnet.wupl.uplvaccinatiegegevens;

import org.taktik.connector.business.domain.kmehr.v20161201.be.fgov.ehealth.standards.kmehr.schema.v1.KmehrmessageType;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.vaccinnet.be/wupl/UPLVaccinatieGegevens}extraInfo"/&gt;
 *         &lt;element ref="{http://www.ehealth.fgov.be/standards/kmehr/schema/v1}kmehrmessage"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extraInfo",
    "kmehrmessage"
})
@XmlRootElement(name = "GetAanvullingVaccinatieGegevensRequest")
public class GetAanvullingVaccinatieGegevensRequest {

    @XmlElement(required = true)
    protected ExtraInfo extraInfo;
    @XmlElement(namespace = "http://www.ehealth.fgov.be/standards/kmehr/schema/v1", required = true)
    protected KmehrmessageType kmehrmessage;

    /**
     * Gets the value of the extraInfo property.
     *
     * @return
     *     possible object is
     *     {@link ExtraInfo }
     *
     */
    public ExtraInfo getExtraInfo() {
        return extraInfo;
    }

    /**
     * Sets the value of the extraInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link ExtraInfo }
     *
     */
    public void setExtraInfo(ExtraInfo value) {
        this.extraInfo = value;
    }

    /**
     * Gets the value of the kmehrmessage property.
     *
     * @return
     *     possible object is
     *     {@link KmehrmessageType }
     *
     */
    public KmehrmessageType getKmehrmessage() {
        return kmehrmessage;
    }

    /**
     * Sets the value of the kmehrmessage property.
     *
     * @param value
     *     allowed object is
     *     {@link KmehrmessageType }
     *
     */
    public void setKmehrmessage(KmehrmessageType value) {
        this.kmehrmessage = value;
    }

}
