//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.02.03 at 10:56:17 AM CET
//


package be.vaccinnet.wupl.uplvaccinatiegegevens;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="folderResult" type="{http://www.vaccinnet.be/wupl/UPLVaccinatieGegevens}FolderResultType" maxOccurs="unbounded"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="foutCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="foutOmschrijving" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "folderResult",
    "foutCode",
    "foutOmschrijving"
})
@XmlRootElement(name = "GetResultaatVerwerkingVaccinatieGegevensResponse")
public class GetResultaatVerwerkingVaccinatieGegevensResponse {

    protected List<FolderResultType> folderResult;
    protected String foutCode;
    protected String foutOmschrijving;

    /**
     * Gets the value of the folderResult property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the folderResult property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFolderResult().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FolderResultType }
     *
     *
     */
    public List<FolderResultType> getFolderResult() {
        if (folderResult == null) {
            folderResult = new ArrayList<FolderResultType>();
        }
        return this.folderResult;
    }

    /**
     * Gets the value of the foutCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFoutCode() {
        return foutCode;
    }

    /**
     * Sets the value of the foutCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFoutCode(String value) {
        this.foutCode = value;
    }

    /**
     * Gets the value of the foutOmschrijving property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFoutOmschrijving() {
        return foutOmschrijving;
    }

    /**
     * Sets the value of the foutOmschrijving property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFoutOmschrijving(String value) {
        this.foutOmschrijving = value;
    }

}
