//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 10:56:17 AM CET 
//


package be.vaccinnet.wupl.uplvaccinatiegegevens;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.vaccinnet.wupl.uplvaccinatiegegevens package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.vaccinnet.wupl.uplvaccinatiegegevens
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAanleverenVaccinatieGegevensRequest }
     * 
     */
    public GetAanleverenVaccinatieGegevensRequest createGetAanleverenVaccinatieGegevensRequest() {
        return new GetAanleverenVaccinatieGegevensRequest();
    }

    /**
     * Create an instance of {@link ExtraInfo }
     * 
     */
    public ExtraInfo createExtraInfo() {
        return new ExtraInfo();
    }

    /**
     * Create an instance of {@link GetAanvullingVaccinatieGegevensRequest }
     * 
     */
    public GetAanvullingVaccinatieGegevensRequest createGetAanvullingVaccinatieGegevensRequest() {
        return new GetAanvullingVaccinatieGegevensRequest();
    }

    /**
     * Create an instance of {@link GetAanleverenVaccinatieGegevensResponse }
     * 
     */
    public GetAanleverenVaccinatieGegevensResponse createGetAanleverenVaccinatieGegevensResponse() {
        return new GetAanleverenVaccinatieGegevensResponse();
    }

    /**
     * Create an instance of {@link GetResultaatVerwerkingVaccinatieGegevensRequest }
     * 
     */
    public GetResultaatVerwerkingVaccinatieGegevensRequest createGetResultaatVerwerkingVaccinatieGegevensRequest() {
        return new GetResultaatVerwerkingVaccinatieGegevensRequest();
    }

    /**
     * Create an instance of {@link GetResultaatVerwerkingVaccinatieGegevensResponse }
     * 
     */
    public GetResultaatVerwerkingVaccinatieGegevensResponse createGetResultaatVerwerkingVaccinatieGegevensResponse() {
        return new GetResultaatVerwerkingVaccinatieGegevensResponse();
    }

    /**
     * Create an instance of {@link FolderResultType }
     * 
     */
    public FolderResultType createFolderResultType() {
        return new FolderResultType();
    }

    /**
     * Create an instance of {@link TransactionResultType }
     * 
     */
    public TransactionResultType createTransactionResultType() {
        return new TransactionResultType();
    }

}
