//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 10:56:17 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.vaccinnet.be/wupl/UPLVaccinatieGegevens", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.vaccinnet.wupl.uplvaccinatiegegevens;
