//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.02.03 at 10:56:17 AM CET
//


package be.vaccinnet.wupl.uplvaccinatiegegevens;

import be.fgov.ehealth.standards.kmehr.id.v1.IDKMEHR;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 *
 *                 TransactionResultType bevat een id (een volgnummer), een code en een omschrijving.
 *                 Dit type bevat gegevens over de verwerking van de vaccinaties. De code dient om
 *                 aan te geven of de verwerking gelukt is, de omschrijving dient om de code te
 *                 verduidelijken.
 *
 *
 * <p>Java class for TransactionResultType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TransactionResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.ehealth.fgov.be/standards/kmehr/id/v1}ID-KMEHR" maxOccurs="unbounded"/&gt;
 *         &lt;element name="resultCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="resultTekst" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionResultType", propOrder = {
    "id",
    "resultCode",
    "resultTekst"
})
public class TransactionResultType {

    @XmlElement(required = true)
    protected List<IDKMEHR> id;
    @XmlElement(required = true)
    protected String resultCode;
    protected String resultTekst;

    /**
     * Gets the value of the id property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDKMEHR }
     *
     *
     */
    public List<IDKMEHR> getId() {
        if (id == null) {
            id = new ArrayList<IDKMEHR>();
        }
        return this.id;
    }

    /**
     * Gets the value of the resultCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultTekst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getResultTekst() {
        return resultTekst;
    }

    /**
     * Sets the value of the resultTekst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setResultTekst(String value) {
        this.resultTekst = value;
    }

}
