//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.29 at 05:57:25 PM CEST
//


package org.taktik.icure.cin.saml.extensions;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdviceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AdviceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:be:cin:nippin:memberdata:saml:extension}AdviceBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:be:cin:nippin:memberdata:saml:extension}AssertionType"/&gt;
 *         &lt;element ref="{urn:be:cin:nippin:memberdata:saml:extension}Facet" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdviceType", propOrder = {
    "assertionType",
    "facets"
})
public class AdviceType
    extends AdviceBaseType
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "AssertionType", required = true)
    protected String assertionType;
    @XmlElement(name = "Facet", required = true)
    protected List<Facet> facets;

    /**
     * Gets the value of the assertionType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAssertionType() {
        return assertionType;
    }

    /**
     * Sets the value of the assertionType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAssertionType(String value) {
        this.assertionType = value;
    }

    /**
     * Gets the value of the facets property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facets property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacets().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Facet }
     *
     *
     */
    public List<Facet> getFacets() {
        if (facets == null) {
            facets = new ArrayList<Facet>();
        }
        return this.facets;
    }

}
