//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.29 at 05:57:25 PM CEST
//


package org.taktik.icure.cin.saml.extensions;

import org.taktik.icure.cin.saml.oasis.names.tc.saml._2_0.protocol.AttributeQuery;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtensionsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ExtensionsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{urn:oasis:names:tc:SAML:2.0:protocol}ExtensionsType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{urn:be:cin:nippin:memberdata:saml:extension}Facet" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtensionsType")
public class ExtensionsType
    extends org.taktik.icure.cin.saml.oasis.names.tc.saml._2_0.protocol.ExtensionsType
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "Facet", namespace = "urn:be:cin:nippin:memberdata:saml:extension")
    protected List<Facet> facets;

    public List<Facet> getFacets() {
        if (facets == null) {
            facets = new ArrayList<>();
        }

        return facets;
    }
}
