//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.29 at 05:57:25 PM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:be:cin:nippin:memberdata:saml:extension", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.taktik.icure.cin.saml.extensions;
