package be.fgov.ehealth.standards.kmehr.mycarenet.cd.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(
   name = "CD-COUNTRYvalues"
)
@XmlEnum
public enum CDCOUNTRYvalues {
   @XmlEnumValue("ad")
   AD("ad"),
   @XmlEnumValue("ae")
   AE("ae"),
   @XmlEnumValue("af")
   AF("af"),
   @XmlEnumValue("ag")
   AG("ag"),
   @XmlEnumValue("ai")
   AI("ai"),
   @XmlEnumValue("al")
   AL("al"),
   @XmlEnumValue("am")
   AM("am"),
   @XmlEnumValue("an")
   AN("an"),
   @XmlEnumValue("ao")
   AO("ao"),
   @XmlEnumValue("aq")
   AQ("aq"),
   @XmlEnumValue("ar")
   AR("ar"),
   @XmlEnumValue("arpa")
   ARPA("arpa"),
   @XmlEnumValue("as")
   AS("as"),
   @XmlEnumValue("at")
   AT("at"),
   @XmlEnumValue("au")
   AU("au"),
   @XmlEnumValue("aw")
   AW("aw"),
   @XmlEnumValue("az")
   AZ("az"),
   @XmlEnumValue("ba")
   BA("ba"),
   @XmlEnumValue("bb")
   BB("bb"),
   @XmlEnumValue("bd")
   BD("bd"),
   @XmlEnumValue("be")
   BE("be"),
   @XmlEnumValue("bf")
   BF("bf"),
   @XmlEnumValue("bg")
   BG("bg"),
   @XmlEnumValue("bh")
   BH("bh"),
   @XmlEnumValue("bi")
   BI("bi"),
   @XmlEnumValue("bj")
   BJ("bj"),
   @XmlEnumValue("bm")
   BM("bm"),
   @XmlEnumValue("bn")
   BN("bn"),
   @XmlEnumValue("bo")
   BO("bo"),
   @XmlEnumValue("br")
   BR("br"),
   @XmlEnumValue("bs")
   BS("bs"),
   @XmlEnumValue("bt")
   BT("bt"),
   @XmlEnumValue("bv")
   BV("bv"),
   @XmlEnumValue("bw")
   BW("bw"),
   @XmlEnumValue("by")
   BY("by"),
   @XmlEnumValue("bz")
   BZ("bz"),
   @XmlEnumValue("ca")
   CA("ca"),
   @XmlEnumValue("cc")
   CC("cc"),
   @XmlEnumValue("cf")
   CF("cf"),
   @XmlEnumValue("cd")
   CD("cd"),
   @XmlEnumValue("cg")
   CG("cg"),
   @XmlEnumValue("ch")
   CH("ch"),
   @XmlEnumValue("ci")
   CI("ci"),
   @XmlEnumValue("ck")
   CK("ck"),
   @XmlEnumValue("cl")
   CL("cl"),
   @XmlEnumValue("cm")
   CM("cm"),
   @XmlEnumValue("cn")
   CN("cn"),
   @XmlEnumValue("co")
   CO("co"),
   @XmlEnumValue("com")
   COM("com"),
   @XmlEnumValue("cr")
   CR("cr"),
   @XmlEnumValue("cs")
   CS("cs"),
   @XmlEnumValue("cu")
   CU("cu"),
   @XmlEnumValue("cv")
   CV("cv"),
   @XmlEnumValue("cx")
   CX("cx"),
   @XmlEnumValue("cy")
   CY("cy"),
   @XmlEnumValue("cz")
   CZ("cz"),
   @XmlEnumValue("de")
   DE("de"),
   @XmlEnumValue("dj")
   DJ("dj"),
   @XmlEnumValue("dk")
   DK("dk"),
   @XmlEnumValue("dm")
   DM("dm"),
   @XmlEnumValue("do")
   DO("do"),
   @XmlEnumValue("dz")
   DZ("dz"),
   @XmlEnumValue("ec")
   EC("ec"),
   @XmlEnumValue("edu")
   EDU("edu"),
   @XmlEnumValue("ee")
   EE("ee"),
   @XmlEnumValue("eg")
   EG("eg"),
   @XmlEnumValue("eh")
   EH("eh"),
   @XmlEnumValue("er")
   ER("er"),
   @XmlEnumValue("es")
   ES("es"),
   @XmlEnumValue("et")
   ET("et"),
   @XmlEnumValue("fi")
   FI("fi"),
   @XmlEnumValue("fj")
   FJ("fj"),
   @XmlEnumValue("fk")
   FK("fk"),
   @XmlEnumValue("fm")
   FM("fm"),
   @XmlEnumValue("fo")
   FO("fo"),
   @XmlEnumValue("fr")
   FR("fr"),
   @XmlEnumValue("fx")
   FX("fx"),
   @XmlEnumValue("ga")
   GA("ga"),
   @XmlEnumValue("gb")
   GB("gb"),
   @XmlEnumValue("gd")
   GD("gd"),
   @XmlEnumValue("ge")
   GE("ge"),
   @XmlEnumValue("gf")
   GF("gf"),
   @XmlEnumValue("gh")
   GH("gh"),
   @XmlEnumValue("gi")
   GI("gi"),
   @XmlEnumValue("gl")
   GL("gl"),
   @XmlEnumValue("gm")
   GM("gm"),
   @XmlEnumValue("gn")
   GN("gn"),
   @XmlEnumValue("gov")
   GOV("gov"),
   @XmlEnumValue("gp")
   GP("gp"),
   @XmlEnumValue("gr")
   GR("gr"),
   @XmlEnumValue("gs")
   GS("gs"),
   @XmlEnumValue("gt")
   GT("gt"),
   @XmlEnumValue("gu")
   GU("gu"),
   @XmlEnumValue("gw")
   GW("gw"),
   @XmlEnumValue("gy")
   GY("gy"),
   @XmlEnumValue("hk")
   HK("hk"),
   @XmlEnumValue("hm")
   HM("hm"),
   @XmlEnumValue("hn")
   HN("hn"),
   @XmlEnumValue("hr")
   HR("hr"),
   @XmlEnumValue("ht")
   HT("ht"),
   @XmlEnumValue("hu")
   HU("hu"),
   @XmlEnumValue("id")
   ID("id"),
   @XmlEnumValue("ie")
   IE("ie"),
   @XmlEnumValue("il")
   IL("il"),
   @XmlEnumValue("in")
   IN("in"),
   @XmlEnumValue("int")
   INT("int"),
   @XmlEnumValue("io")
   IO("io"),
   @XmlEnumValue("iq")
   IQ("iq"),
   @XmlEnumValue("ir")
   IR("ir"),
   @XmlEnumValue("is")
   IS("is"),
   @XmlEnumValue("it")
   IT("it"),
   @XmlEnumValue("jm")
   JM("jm"),
   @XmlEnumValue("jo")
   JO("jo"),
   @XmlEnumValue("jp")
   JP("jp"),
   @XmlEnumValue("ke")
   KE("ke"),
   @XmlEnumValue("kg")
   KG("kg"),
   @XmlEnumValue("kh")
   KH("kh"),
   @XmlEnumValue("ki")
   KI("ki"),
   @XmlEnumValue("km")
   KM("km"),
   @XmlEnumValue("kn")
   KN("kn"),
   @XmlEnumValue("kp")
   KP("kp"),
   @XmlEnumValue("kr")
   KR("kr"),
   @XmlEnumValue("kw")
   KW("kw"),
   @XmlEnumValue("ky")
   KY("ky"),
   @XmlEnumValue("kz")
   KZ("kz"),
   @XmlEnumValue("la")
   LA("la"),
   @XmlEnumValue("lb")
   LB("lb"),
   @XmlEnumValue("lc")
   LC("lc"),
   @XmlEnumValue("li")
   LI("li"),
   @XmlEnumValue("lk")
   LK("lk"),
   @XmlEnumValue("ls")
   LS("ls"),
   @XmlEnumValue("lt")
   LT("lt"),
   @XmlEnumValue("lu")
   LU("lu"),
   @XmlEnumValue("lv")
   LV("lv"),
   @XmlEnumValue("ly")
   LY("ly"),
   @XmlEnumValue("ma")
   MA("ma"),
   @XmlEnumValue("mc")
   MC("mc"),
   @XmlEnumValue("md")
   MD("md"),
   @XmlEnumValue("mg")
   MG("mg"),
   @XmlEnumValue("mh")
   MH("mh"),
   @XmlEnumValue("mil")
   MIL("mil"),
   @XmlEnumValue("mk")
   MK("mk"),
   @XmlEnumValue("ml")
   ML("ml"),
   @XmlEnumValue("mm")
   MM("mm"),
   @XmlEnumValue("mn")
   MN("mn"),
   @XmlEnumValue("mo")
   MO("mo"),
   @XmlEnumValue("mp")
   MP("mp"),
   @XmlEnumValue("mq")
   MQ("mq"),
   @XmlEnumValue("mr")
   MR("mr"),
   @XmlEnumValue("ms")
   MS("ms"),
   @XmlEnumValue("mt")
   MT("mt"),
   @XmlEnumValue("mu")
   MU("mu"),
   @XmlEnumValue("mv")
   MV("mv"),
   @XmlEnumValue("mw")
   MW("mw"),
   @XmlEnumValue("mx")
   MX("mx"),
   @XmlEnumValue("my")
   MY("my"),
   @XmlEnumValue("mz")
   MZ("mz"),
   @XmlEnumValue("na")
   NA("na"),
   @XmlEnumValue("nato")
   NATO("nato"),
   @XmlEnumValue("nc")
   NC("nc"),
   @XmlEnumValue("ne")
   NE("ne"),
   @XmlEnumValue("net")
   NET("net"),
   @XmlEnumValue("nf")
   NF("nf"),
   @XmlEnumValue("ng")
   NG("ng"),
   @XmlEnumValue("ni")
   NI("ni"),
   @XmlEnumValue("nl")
   NL("nl"),
   @XmlEnumValue("no")
   NO("no"),
   @XmlEnumValue("np")
   NP("np"),
   @XmlEnumValue("nr")
   NR("nr"),
   @XmlEnumValue("nt")
   NT("nt"),
   @XmlEnumValue("nu")
   NU("nu"),
   @XmlEnumValue("nz")
   NZ("nz"),
   @XmlEnumValue("om")
   OM("om"),
   @XmlEnumValue("org")
   ORG("org"),
   @XmlEnumValue("pa")
   PA("pa"),
   @XmlEnumValue("pe")
   PE("pe"),
   @XmlEnumValue("pf")
   PF("pf"),
   @XmlEnumValue("pg")
   PG("pg"),
   @XmlEnumValue("ph")
   PH("ph"),
   @XmlEnumValue("pk")
   PK("pk"),
   @XmlEnumValue("pl")
   PL("pl"),
   @XmlEnumValue("pm")
   PM("pm"),
   @XmlEnumValue("pn")
   PN("pn"),
   @XmlEnumValue("pr")
   PR("pr"),
   @XmlEnumValue("pt")
   PT("pt"),
   @XmlEnumValue("pw")
   PW("pw"),
   @XmlEnumValue("py")
   PY("py"),
   @XmlEnumValue("qa")
   QA("qa"),
   @XmlEnumValue("re")
   RE("re"),
   @XmlEnumValue("ro")
   RO("ro"),
   @XmlEnumValue("ru")
   RU("ru"),
   @XmlEnumValue("rw")
   RW("rw"),
   @XmlEnumValue("sa")
   SA("sa"),
   @XmlEnumValue("sb")
   SB("sb"),
   @XmlEnumValue("sc")
   SC("sc"),
   @XmlEnumValue("sd")
   SD("sd"),
   @XmlEnumValue("se")
   SE("se"),
   @XmlEnumValue("sg")
   SG("sg"),
   @XmlEnumValue("sh")
   SH("sh"),
   @XmlEnumValue("si")
   SI("si"),
   @XmlEnumValue("sj")
   SJ("sj"),
   @XmlEnumValue("sk")
   SK("sk"),
   @XmlEnumValue("sl")
   SL("sl"),
   @XmlEnumValue("sm")
   SM("sm"),
   @XmlEnumValue("sn")
   SN("sn"),
   @XmlEnumValue("so")
   SO("so"),
   @XmlEnumValue("sr")
   SR("sr"),
   @XmlEnumValue("st")
   ST("st"),
   @XmlEnumValue("su")
   SU("su"),
   @XmlEnumValue("sv")
   SV("sv"),
   @XmlEnumValue("sy")
   SY("sy"),
   @XmlEnumValue("sz")
   SZ("sz"),
   @XmlEnumValue("tc")
   TC("tc"),
   @XmlEnumValue("td")
   TD("td"),
   @XmlEnumValue("tf")
   TF("tf"),
   @XmlEnumValue("tg")
   TG("tg"),
   @XmlEnumValue("th")
   TH("th"),
   @XmlEnumValue("tj")
   TJ("tj"),
   @XmlEnumValue("tk")
   TK("tk"),
   @XmlEnumValue("tm")
   TM("tm"),
   @XmlEnumValue("tn")
   TN("tn"),
   @XmlEnumValue("to")
   TO("to"),
   @XmlEnumValue("tp")
   TP("tp"),
   @XmlEnumValue("tr")
   TR("tr"),
   @XmlEnumValue("tt")
   TT("tt"),
   @XmlEnumValue("tv")
   TV("tv"),
   @XmlEnumValue("tw")
   TW("tw"),
   @XmlEnumValue("tz")
   TZ("tz"),
   @XmlEnumValue("ua")
   UA("ua"),
   @XmlEnumValue("ug")
   UG("ug"),
   @XmlEnumValue("uk")
   UK("uk"),
   @XmlEnumValue("um")
   UM("um"),
   @XmlEnumValue("us")
   US("us"),
   @XmlEnumValue("uy")
   UY("uy"),
   @XmlEnumValue("uz")
   UZ("uz"),
   @XmlEnumValue("va")
   VA("va"),
   @XmlEnumValue("vc")
   VC("vc"),
   @XmlEnumValue("ve")
   VE("ve"),
   @XmlEnumValue("vg")
   VG("vg"),
   @XmlEnumValue("vi")
   VI("vi"),
   @XmlEnumValue("vn")
   VN("vn"),
   @XmlEnumValue("vu")
   VU("vu"),
   @XmlEnumValue("wf")
   WF("wf"),
   @XmlEnumValue("ws")
   WS("ws"),
   @XmlEnumValue("ye")
   YE("ye"),
   @XmlEnumValue("yt")
   YT("yt"),
   @XmlEnumValue("yu")
   YU("yu"),
   @XmlEnumValue("za")
   ZA("za"),
   @XmlEnumValue("zm")
   ZM("zm"),
   @XmlEnumValue("zr")
   ZR("zr"),
   @XmlEnumValue("zw")
   ZW("zw");

   private final String value;

   private CDCOUNTRYvalues(String v) {
      this.value = v;
   }

   public String value() {
      return this.value;
   }

   public static CDCOUNTRYvalues fromValue(String v) {
      CDCOUNTRYvalues[] arr$ = values();
      int len$ = arr$.length;

      for(int i$ = 0; i$ < len$; ++i$) {
         CDCOUNTRYvalues c = arr$[i$];
         if (c.value.equals(v)) {
            return c;
         }
      }

      throw new IllegalArgumentException(v);
   }
}
