<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:chiv="urn:be:fgov:ehealth:chap4:protocol:v1"
    xmlns:err="urn:be:fgov:ehealth:errors:soa:v1"
    xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    name="Chap4AgreementConsultationWebservice"
    targetNamespace="urn:be:fgov:ehealth:chap4:protocol:v1"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:documentation>Version 1.0</wsdl:documentation>
    <wsdl:types>
        <xsd:schema>
            <xsd:import
                namespace="urn:be:fgov:ehealth:chap4:protocol:v1"
                schemaLocation="../XSD/chap4services_protocol-1_0.xsd" />
            <xsd:import
                namespace="urn:be:fgov:ehealth:errors:soa:v1"
                schemaLocation="../../ehealth-errors/XSD/ehealth-errors-schema-soa-1_1.xsd" />
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="ConsultChap4MedicalAdvisorAgreementRequest">
        <wsdl:part
            element="chiv:ConsultChap4MedicalAdvisorAgreementRequest"
            name="body" />
    </wsdl:message>
    <wsdl:message name="ConsultChap4MedicalAdvisorAgreementResponse">
        <wsdl:part
            element="chiv:ConsultChap4MedicalAdvisorAgreementResponse"
            name="body" />
    </wsdl:message>
    <wsdl:message name="SystemError">
        <wsdl:part
            element="err:SystemError"
            name="fault" />
    </wsdl:message>
    <wsdl:portType name="Chap4AgreementConsultationPortType">
        <wsdl:operation name="consultChap4MedicalAdvisorAgreement">
            <wsdl:input message="chiv:ConsultChap4MedicalAdvisorAgreementRequest" />
            <wsdl:output message="chiv:ConsultChap4MedicalAdvisorAgreementResponse" />
            <wsdl:fault
                message="chiv:SystemError"
                name="SystemError" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding
        name="Chap4AgreementConsultationSoapBinding"
        type="chiv:Chap4AgreementConsultationPortType">
        <soap11:binding
            style="document"
            transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="consultChap4MedicalAdvisorAgreement">
            <soap11:operation
                soapAction="urn:be:fgov:ehealth:chap4:protocol:v1:ConsultChap4MedicalAdvisorAgreement"
                style="document" />
            <wsdl:input>
                <soap11:body use="literal" />
                <PolicyReference
                    URI="#SAML_HOK"
                    xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy" />
            </wsdl:input>
            <wsdl:output>
                <soap11:body use="literal" />
            </wsdl:output>
            <wsdl:fault name="SystemError">
                <soap11:fault
                    name="SystemError"
                    use="literal" />
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="Chap4AgreementConsultationService">
        <wsdl:port
            binding="chiv:Chap4AgreementConsultationSoapBinding"
            name="Chap4AgreementConsultationServiceSOAP11">
            <soap11:address
                location="https://services.ehealth.fgov.be/ChapterIV/ChapterIVAgreementConsultation/v1" />
        </wsdl:port>
    </wsdl:service>
    <wsp:Policy
        xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
        xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        wsu:Id="SAML_HOK">
        <sp:AsymmetricBinding>
            <wsp:Policy>
                <sp:InitiatorToken>
                    <wsp:Policy>
                        <sp:SamlToken
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV11Token10 />
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:InitiatorToken>
                <sp:RecipientToken>
                    <wsp:Policy>
                        <sp:X509Token
                            sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
                            <wsp:Policy>
                                <sp:WssX509V3Token10 />
                            </wsp:Policy>
                        </sp:X509Token>
                    </wsp:Policy>
                </sp:RecipientToken>
                <sp:AlgorithmSuite>
                    <wsp:Policy>
                        <sp:Basic256 />
                    </wsp:Policy>
                </sp:AlgorithmSuite>
                <sp:Layout>
                    <wsp:Policy>
                        <sp:Lax />
                    </wsp:Policy>
                </sp:Layout>
                <sp:IncludeTimestamp />
                <sp:ProtectTokens />
                <sp:OnlySignEntireHeadersAndBody />
            </wsp:Policy>
        </sp:AsymmetricBinding>
        <sp:Wss10>
            <wsp:Policy>
                <sp:MustSupportRefKeyIdentifier />
                <sp:MustSupportRefIssuerSerial />
            </wsp:Policy>
        </sp:Wss10>
        <sp:SignedParts>
            <sp:Body />
        </sp:SignedParts>
    </wsp:Policy>
</wsdl:definitions>
